Sign every xcframework slice (#37)
Update build environment

diff --git a/scripts/bootstrap b/scripts/bootstrap
--- a/scripts/bootstrap
+++ b/scripts/bootstrap
@@ -12,16 +12,25 @@ hash brew 2>/dev/null || {
   exit 1;
 }
 
-brew bundle check >/dev/null 2>&1  || {
-  echo "==> Installing Homebrew dependencies…"
-  brew bundle
-}
+if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
+  hash brew 2>/dev/null || {
+    echo >&2 "The command 'brew' is required but not installed. See https://brew.sh for installation guidelines.";
+    exit 1;
+  }
+
+  brew bundle check >/dev/null 2>&1  || {
+    echo "==> Installing Homebrew dependencies…"
+    brew bundle
+  }
+fi
 
 mint bootstrap
 
-hash bundle 2>/dev/null || {
-  echo "==> Installing Bundler 2.0.1…"
-  gem install bundler -v 2.0.1 --no-document --quiet
-}
-echo "==> Installing gem dependencies…"
-bundle install --system
+if [ -f "Gemfile" ]; then
+  hash bundle 2>/dev/null || {
+    echo "==> Installing Bundler 4.0.6…"
+    gem install bundler -v 4.0.6 --no-document --quiet
+  }
+  echo "==> Installing gem dependencies…"
+  bundle install
+fi
